# Step 1: Use an official JDK image as a base
FROM openjdk:17-jdk-alpine
WORKDIR /app

# Step 3: Copy the built jar file into the container
COPY target/producer-0.0.1-SNAPSHOT.jar ./producer-app.jar

# Step 4: Specify the default command
# This allows passing arguments from docker-compose or at runtime.
ENTRYPOINT ["java", "-jar", "producer-app.jar"]