app:
  deviceId: testDefaultDeviceId
  deviceName: testDefaultDeviceName
  startLatitude: 50.0
  startLongitude: 50.0
  endLatitude: 51.0
  endLongitude: 51.0
  speed: 0.1
  interval: 10000
kafka:
  bootstrap-servers: localhost:9092
  topic: TEST_TOPIC